/**
 * useExport — Export chat conversation as Markdown (.md) or PDF (browser print).
 * Markdown: formats messages with metadata header, source citations, and confidence scores.
 * PDF: injects print-optimized CSS and triggers window.print().
 * Connected to: ChatMessage (action buttons), page.tsx (export full chat).
 */

import { useCallback } from 'react';

export interface ExportMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: Date;
  citations?: Array<{ id: number; title: string; url: string; source_type?: string }>;
  confidence?: { score: number; label: string };
}

export interface UseExportReturn {
  exportAsMarkdown: (messages: ExportMessage[], title?: string) => void;
  exportAsPDF: (title?: string) => void;
  exportMessageAsMarkdown: (message: ExportMessage) => void;
}

/** Format a single message as Markdown block */
function formatMessageMarkdown(message: ExportMessage): string {
  const role = message.role === 'user' ? '## Question' : '## Answer';
  const timestamp = message.timestamp
    ? `\n*${message.timestamp.toLocaleString()}*\n`
    : '';
  let block = `${role}${timestamp}\n\n${message.content}\n`;

  if (message.role === 'assistant' && message.citations?.length) {
    block += '\n### Sources\n';
    for (const c of message.citations) {
      block += `${c.id}. [${c.title || c.url}](${c.url})\n`;
    }
  }

  if (message.confidence) {
    block += `\n*Confidence: ${message.confidence.score}% (${message.confidence.label})*\n`;
  }

  return block;
}

/** Trigger browser file download with given content */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function useExport(): UseExportReturn {
  /** Export full conversation as a .md file */
  const exportAsMarkdown = useCallback((messages: ExportMessage[], title = 'Nurav Research') => {
    const safeTitle = title.replace(/[^a-z0-9\s-]/gi, '').trim() || 'nurav-research';
    const dateStr = new Date().toISOString().split('T')[0];

    const header = [
      `# ${title}`,
      `> Exported from Nurav AI on ${new Date().toLocaleString()}`,
      '',
      '---',
      '',
    ].join('\n');

    const body = messages.map(formatMessageMarkdown).join('\n---\n\n');
    const footer = '\n\n---\n*Generated by [Nurav AI](https://nurav.ai)*\n';

    downloadFile(
      header + body + footer,
      `${safeTitle.toLowerCase().replace(/\s+/g, '-')}-${dateStr}.md`,
      'text/markdown'
    );
  }, []);

  /** Export single assistant message as .md */
  const exportMessageAsMarkdown = useCallback((message: ExportMessage) => {
    const content = formatMessageMarkdown(message);
    const dateStr = new Date().toISOString().split('T')[0];
    downloadFile(content, `nurav-answer-${dateStr}.md`, 'text/markdown');
  }, []);

  /** Trigger browser print dialog — use CSS @media print for styling */
  const exportAsPDF = useCallback((title = 'Nurav Research') => {
    const originalTitle = document.title;
    document.title = title;

    // Inject print styles if not already present
    const styleId = 'nurav-print-styles';
    if (!document.getElementById(styleId)) {
      const style = document.createElement('style');
      style.id = styleId;
      style.textContent = `
        @media print {
          body > * { display: none !important; }
          .nurav-printable { display: block !important; }
          .nurav-printable { font-family: Georgia, serif; font-size: 12pt; line-height: 1.6; color: #000; }
          .nurav-printable h2 { font-size: 14pt; font-weight: bold; margin-top: 16pt; border-bottom: 1px solid #ccc; }
          .nurav-printable a { color: #1a0dab; text-decoration: underline; }
          .nurav-no-print { display: none !important; }
          [class*="actions"], [class*="followup"], [class*="sidebar"], [class*="input"], [class*="header"] { display: none !important; }
          [class*="messagesContainer"], [class*="answerContainer"], [class*="userQuestion"] { display: block !important; }
        }
      `;
      document.head.appendChild(style);
    }

    window.print();
    document.title = originalTitle;
  }, []);

  return { exportAsMarkdown, exportAsPDF, exportMessageAsMarkdown };
}
